/*
 * Park Manor Test Cases
 *
 * Structure: an array of categories, each with tests.
 * Each test has:
 *   id       — unique short id (used as localStorage key suffix)
 *   title    — short name
 *   pre      — preconditions (what state to be in)
 *   steps    — array of numbered steps
 *   expect   — expected outcome
 *   roles    — which roles this test applies to (for filtering)
 *   priority — 'critical' | 'high' | 'medium' | 'low'
 */
window.PARK_MANOR_TESTS = [
  {
    id: 'auth',
    name: 'Authentication & session',
    icon: '🔐',
    tests: [
      {id:'auth-001', title:'Fresh page load shows hard-wall login', pre:'Not signed in, no session token', steps:['Load the app URL'], expect:'Login modal appears immediately and cannot be dismissed by clicking outside or pressing Escape. No underlying content is visible or interactive.', roles:['all'], priority:'critical'},
      {id:'auth-002', title:'Valid username + password logs in', pre:'Hard-wall login modal visible; a valid user exists', steps:['Enter valid username','Enter correct password','Click Log in'], expect:'Modal closes; main app renders; user\'s role-appropriate view appears (trustee sees Awaiting Trustee Approval chip pre-selected, others see default active statuses).', roles:['all'], priority:'critical'},
      {id:'auth-003', title:'Wrong password shows error, does not log in', pre:'Hard-wall login modal visible', steps:['Enter valid username','Enter wrong password','Click Log in'], expect:'Error message appears; modal stays open; nothing else changes.', roles:['all'], priority:'critical'},
      {id:'auth-004', title:'Empty username rejected', pre:'Login modal visible', steps:['Leave username empty','Enter any password','Click Log in'], expect:'Error message; no login attempt made.', roles:['all'], priority:'high'},
      {id:'auth-005', title:'Empty password rejected', pre:'Login modal visible', steps:['Enter valid username','Leave password empty','Click Log in'], expect:'Error message; no login attempt made.', roles:['all'], priority:'high'},
      {id:'auth-006', title:'Session persists across page reload', pre:'Logged in successfully', steps:['Reload the page (F5 / Cmd+R)'], expect:'App comes back logged in as the same user without showing the login modal.', roles:['all'], priority:'critical'},
      {id:'auth-007', title:'Logout re-opens hard-wall login', pre:'Logged in', steps:['Click Logout in the header/menu'], expect:'App state clears; hard-wall login modal opens; main app hidden.', roles:['all'], priority:'critical'},
      {id:'auth-008', title:'Post-login prompt to change password', pre:'Fresh password login (not passkey, not hardcoded admin)', steps:['Log in with password'], expect:'A "Would you like to change your password?" prompt appears with No/Yes options. Clicking No lets user continue to app.', roles:['all except hardcoded admin'], priority:'high'},
      {id:'auth-009', title:'"Yes, change password" opens change modal', pre:'Password change prompt visible after login', steps:['Click "Yes, change now"'], expect:'Change-password modal opens with two password fields.', roles:['all'], priority:'high'},
      {id:'auth-010', title:'Change password accepts any password (no length rule)', pre:'Change-password modal open', steps:['Type "a" in both new and confirm fields','Click Save'], expect:'Password updates; success message; user stays logged in with new password.', roles:['all'], priority:'high'},
      {id:'auth-011', title:'Change password rejects mismatched fields', pre:'Change-password modal open', steps:['Type "abc" in new field','Type "xyz" in confirm field','Click Save'], expect:'Error "Passwords do not match"; no save.', roles:['all'], priority:'high'},
      {id:'auth-012', title:'Change password rejects empty', pre:'Change-password modal open', steps:['Leave both fields empty','Click Save'], expect:'Error "Please enter a password"; no save.', roles:['all'], priority:'high'},
      {id:'auth-013', title:'New password works for next login', pre:'Just changed password to something known', steps:['Log out','Log in with old password'], expect:'Old password fails; then log in with new password succeeds.', roles:['all'], priority:'critical'},
      {id:'auth-014', title:'Admin can reset another user\'s password', pre:'Logged in as admin; another user exists', steps:['Open user-edit modal for another user','Type new password','Click Save'], expect:'Password saves. That user can now log in with the new password.', roles:['admin'], priority:'critical'},
      {id:'auth-015', title:'Blank password field on user edit preserves existing', pre:'Editing an existing user with a set password', steps:['Leave password field blank','Change some other field (e.g. full name)','Save'], expect:'User can still log in with their old password. The blank field did not overwrite.', roles:['admin'], priority:'high'},
      {id:'auth-016', title:'Password reveal button toggles visibility', pre:'User-edit modal open on a user', steps:['Click the 👁 icon next to the password field'], expect:'Text becomes visible; icon changes to 🙈. Click again → hidden again.', roles:['admin'], priority:'medium'},
      {id:'auth-017', title:'Passkey enrolment prompt after login (if none set)', pre:'Password login as a user with no passkey yet', steps:['Complete password login','Dismiss password-change prompt'], expect:'A passkey enrolment prompt appears offering to add a passkey.', roles:['all'], priority:'medium'},
      {id:'auth-018', title:'Passkey login works after enrolment', pre:'User has a passkey enrolled', steps:['Log out','Choose Passkey option on login screen','Approve on device'], expect:'User signs in without a password prompt.', roles:['all'], priority:'high'},
      {id:'auth-019', title:'Public-mode URLs bypass hard-wall login', pre:'Not logged in', steps:['Load ?contact-public'], expect:'Public form loads; no login modal appears.', roles:['unauth'], priority:'critical'},
      {id:'auth-020', title:'Share-link URLs bypass hard-wall login', pre:'Not logged in; valid share link known', steps:['Load ?share=<id>&t=<token>'], expect:'Read-only share view loads; no login modal.', roles:['unauth'], priority:'critical'},
    ]
  },

  {
    id: 'perms',
    name: 'Permissions framework',
    icon: '🛡️',
    tests: [
      {id:'perms-001', title:'Admin sees Settings button', pre:'Logged in as admin', steps:['Look at header and toolbar'], expect:'⚙ Settings button visible in header AND in secondary toolbar.', roles:['admin'], priority:'critical'},
      {id:'perms-002', title:'Non-admin does NOT see Settings button', pre:'Logged in as trustee, owner, tenant, or viewer', steps:['Look at header and toolbar'], expect:'⚙ Settings button hidden in BOTH locations.', roles:['trustee','owner','tenant','viewer'], priority:'critical'},
      {id:'perms-003', title:'Trustee filter defaults to "Awaiting Trustee Approval" on login', pre:'Trustee just logged in', steps:['Observe the ticket filter chips'], expect:'Only the Awaiting Trustee Approval chip is active. Ticket list shows only those tickets.', roles:['trustee'], priority:'high'},
      {id:'perms-004', title:'Non-trustee filter defaults to active statuses', pre:'Any non-trustee just logged in', steps:['Observe the ticket filter chips'], expect:'Default filter shows active statuses (open, in_progress, awaiting_quote, etc.) but not resolved.', roles:['admin','owner','tenant','viewer'], priority:'high'},
      {id:'perms-005', title:'canDeleteTickets = never hides Delete button', pre:'User has canDeleteTickets set to never or role default is never', steps:['Open any ticket'], expect:'Delete button in ticket modal header is hidden.', roles:['owner','tenant','viewer'], priority:'critical'},
      {id:'perms-006', title:'canDeleteTickets = always shows Delete button', pre:'User has canDeleteTickets = always', steps:['Open any ticket'], expect:'Delete button visible; clicking it prompts confirmation.', roles:['admin'], priority:'critical'},
      {id:'perms-007', title:'canDeleteTickets = own only allows deleting own tickets', pre:'User has canDeleteTickets = own; two tickets exist — one they created, one they didn\'t', steps:['Open the ticket they created','Then open the other'], expect:'Delete button visible on own; hidden on other.', roles:['trustee','owner','tenant'], priority:'high'},
      {id:'perms-008', title:'canEditOthersTickets = false blocks editing others\' tickets', pre:'User has canEditOthersTickets = false; open a ticket they did NOT create', steps:['Try to change the description','Try to change priority'], expect:'Fields are read-only or changes are silently reverted / not saved. Own tickets remain editable.', roles:['trustee','owner','tenant'], priority:'critical'},
      {id:'perms-009', title:'canChangeStatus = false hides status transitions', pre:'User has canChangeStatus = false', steps:['Open any ticket'], expect:'Status stepper does not respond to clicks; status dropdown is disabled or hidden.', roles:['owner','tenant','viewer'], priority:'high'},
      {id:'perms-010', title:'canApproveQuotes = true shows Approve buttons', pre:'Trustee viewing awaiting_trustee_approval ticket with quotes', steps:['Open ticket','Scroll to approval panel'], expect:'✓ Approve button visible per quote/proposal.', roles:['trustee','admin'], priority:'critical'},
      {id:'perms-011', title:'canApproveQuotes = false hides Approve buttons', pre:'User has canApproveQuotes = false', steps:['Open awaiting_trustee_approval ticket'], expect:'No Approve buttons visible.', roles:['owner','tenant','viewer'], priority:'high'},
      {id:'perms-012', title:'canAttachFiles = false hides Camera/Gallery buttons', pre:'User has canAttachFiles = false', steps:['Open any ticket'], expect:'Camera and Gallery buttons in linked-documents section are hidden.', roles:['viewer'], priority:'high'},
      {id:'perms-013', title:'canDeleteAttachments = own only allows deleting own uploads', pre:'User has canDeleteAttachments = own; ticket has attachment they uploaded and one they didn\'t', steps:['Try to unlink each'], expect:'✕ button appears only on own attachment.', roles:['trustee','owner','tenant'], priority:'high'},
      {id:'perms-014', title:'canEditDocuments = false hides doc edit UI', pre:'User has canEditDocuments = false', steps:['Open any invoice/document'], expect:'Invoice edit modal fields are read-only or the edit path is blocked.', roles:['owner','tenant','viewer'], priority:'medium'},
      {id:'perms-015', title:'canShareLink = false hides Share link button', pre:'User has canShareLink = false', steps:['Open any ticket'], expect:'Share link button in ticket modal header is hidden.', roles:['owner','tenant','viewer'], priority:'high'},
      {id:'perms-016', title:'canManageCriteria = true allows adding proposals', pre:'User has canManageCriteria = true', steps:['Open awaiting_trustee_approval ticket','Look at approval panel'], expect:'+ Add proposal button visible at bottom.', roles:['trustee','admin'], priority:'high'},
      {id:'perms-017', title:'canManageCriteria = false hides Add proposal', pre:'User has canManageCriteria = false', steps:['Open awaiting_trustee_approval ticket'], expect:'+ Add proposal button not visible.', roles:['owner','tenant','viewer'], priority:'medium'},
      {id:'perms-018', title:'canMakeAnonymous = true shows Anonymous checkbox', pre:'User has canMakeAnonymous = true', steps:['Open ticket modal'], expect:'Anonymous checkbox visible next to Reported By field.', roles:['admin','trustee'], priority:'medium'},
      {id:'perms-019', title:'canMakeAnonymous = false hides Anonymous checkbox', pre:'User has canMakeAnonymous = false', steps:['Open ticket modal'], expect:'Anonymous checkbox not visible.', roles:['owner','tenant','viewer'], priority:'medium'},
      {id:'perms-020', title:'Admin bypasses all permission gates', pre:'Any permission set to false/never on the admin role', steps:['Attempt the blocked action'], expect:'Admin can still perform it — admin role always wins in resolution order.', roles:['admin'], priority:'critical'},
      {id:'perms-021', title:'Per-user override supersedes role default', pre:'Role default is false; user override for that key is true', steps:['Log in as that user','Attempt the action'], expect:'User CAN perform the action — user override wins over role default.', roles:['all'], priority:'critical'},
      {id:'perms-022', title:'Per-user override to false blocks even when role allows', pre:'Role default is true; user override for that key is false', steps:['Log in as that user','Attempt the action'], expect:'User CANNOT perform the action.', roles:['all'], priority:'critical'},
      {id:'perms-023', title:'Role permissions matrix opens for admin', pre:'Admin logged in', steps:['Settings → Permissions → Role defaults'], expect:'Matrix of roles × permission keys displayed and editable.', roles:['admin'], priority:'high'},
      {id:'perms-024', title:'Toggling a role permission saves', pre:'Role defaults matrix open', steps:['Toggle any cell','Reload the app','Return to the matrix'], expect:'Toggle state persisted.', roles:['admin'], priority:'critical'},
      {id:'perms-025', title:'Per-user permission override UI opens', pre:'Admin editing a user', steps:['Open user permissions section for a user'], expect:'Per-user override matrix appears, distinct from role defaults.', roles:['admin'], priority:'high'},
      {id:'perms-026', title:'Editing per-user overrides does not wipe on re-render', pre:'Editing a user\'s permissions', steps:['Change several toggles rapidly','Wait for auto re-render'], expect:'Edits persist in buffer; are not reset by the re-render.', roles:['admin'], priority:'high'},
      {id:'perms-027', title:'Guest role sees no interactive controls', pre:'Guest session (unusual case)', steps:['Attempt to access ticket lists'], expect:'Read-only view; no create/edit/delete buttons.', roles:['guest'], priority:'medium'},
      {id:'perms-028', title:'Admin sees admin-only settings sections', pre:'Admin logged in', steps:['Open Settings modal'], expect:'🌐 Public reporting section, Permissions section, Devices section all visible.', roles:['admin'], priority:'high'},
      {id:'perms-029', title:'Non-admin trustee cannot see admin-only sections in settings', pre:'Trustee somehow opens Settings via URL manipulation or shared modal', steps:['Access Settings modal'], expect:'Admin-only sections hidden or the whole modal is inaccessible.', roles:['trustee'], priority:'high'},
      {id:'perms-030', title:'Changing role for a user re-applies role permissions', pre:'Admin editing a user, changing their role', steps:['Change role from owner → trustee','Save','Log in as that user'], expect:'User now has trustee-level access; can approve, etc.', roles:['admin'], priority:'high'},
    ]
  },

  {
    id: 'tickets',
    name: 'Ticket lifecycle',
    icon: '🎫',
    tests: [
      {id:'tkt-001', title:'Create ticket with all fields', pre:'Logged in as admin/trustee', steps:['Click New ticket','Fill title, description, priority, category, unit, reporter','Save'], expect:'Ticket appears in list with sequential ticket number; status defaults to Open.', roles:['admin','trustee'], priority:'critical'},
      {id:'tkt-002', title:'Create ticket with only title', pre:'Logged in', steps:['Click New ticket','Fill only title','Save'], expect:'Ticket created; other fields default sensibly.', roles:['admin','trustee'], priority:'high'},
      {id:'tkt-003', title:'Empty title rejected', pre:'New ticket modal', steps:['Leave title empty','Try to save'], expect:'Error message; not saved.', roles:['admin','trustee'], priority:'high'},
      {id:'tkt-004', title:'Auto-save fires on field change', pre:'Existing ticket open', steps:['Change the description','Wait briefly','Reload page','Reopen the ticket'], expect:'Change persisted without explicit save.', roles:['admin','trustee'], priority:'critical'},
      {id:'tkt-005', title:'Ticket appears in filtered list', pre:'Ticket exists in status Open', steps:['Return to ticket list','Ensure Open filter is active'], expect:'Ticket visible in list.', roles:['all'], priority:'critical'},
      {id:'tkt-006', title:'Delete ticket with confirmation', pre:'User has canDeleteTickets; ticket open', steps:['Click Delete in header','Confirm the prompt'], expect:'Ticket removed; user returned to list; ticket no longer appears anywhere.', roles:['admin'], priority:'critical'},
      {id:'tkt-007', title:'Cancel delete prompt does nothing', pre:'Delete prompt visible', steps:['Click Cancel / press Escape'], expect:'Prompt closes; ticket still exists.', roles:['admin'], priority:'high'},
      {id:'tkt-008', title:'Status: Open → In Progress via stepper', pre:'Ticket in Open status', steps:['Click In Progress in the status stepper'], expect:'Status updates; activity log entry added; card style updates in list.', roles:['admin','trustee'], priority:'critical'},
      {id:'tkt-009', title:'Status: In Progress → Obtaining Quotes', pre:'Ticket in In Progress', steps:['Click Obtaining Quotes'], expect:'Status updates; log entry added.', roles:['admin','trustee'], priority:'high'},
      {id:'tkt-010', title:'Status: Obtaining Quotes → Awaiting Trustee Approval', pre:'Ticket in Obtaining Quotes', steps:['Click Awaiting Trustee Approval'], expect:'Status updates; approval panel becomes visible; card gets purple pulse animation in list.', roles:['admin','trustee'], priority:'critical'},
      {id:'tkt-011', title:'Status: Awaiting Approval → Work In Progress (via threshold)', pre:'Ticket has 3 trustees agreed on same item', steps:['Log in as a trustee','Click the green "▶ Start Work" button on that item'], expect:'Status changes to Work In Progress; item marked as approved; activity log records which item was chosen.', roles:['trustee','admin'], priority:'critical'},
      {id:'tkt-012', title:'Status: Work In Progress → Resolved', pre:'Ticket in Work In Progress', steps:['Click Resolved'], expect:'Status updates; date closed can be set.', roles:['admin','trustee'], priority:'high'},
      {id:'tkt-013', title:'Status can move backwards', pre:'Ticket in Awaiting Trustee Approval', steps:['Click Obtaining Quotes to go back'], expect:'Status moves back; approvals may be cleared or preserved (verify by inspecting).', roles:['admin'], priority:'high'},
      {id:'tkt-014', title:'Priority stripe visible on card', pre:'Ticket has priority High', steps:['View ticket in list'], expect:'Amber left border stripe.', roles:['all'], priority:'medium'},
      {id:'tkt-015', title:'Ticket number is sequential', pre:'Multiple tickets exist', steps:['Create a new ticket','Note its ticket number'], expect:'Ticket number is one higher than the previous highest.', roles:['admin','trustee'], priority:'high'},
      {id:'tkt-016', title:'Unit shows on card', pre:'Ticket has unit "5"', steps:['View card in list'], expect:'Small "Unit 5" label appears in card header.', roles:['all'], priority:'medium'},
      {id:'tkt-017', title:'Reporter name saves', pre:'New ticket', steps:['Set reporter to "Test Person"','Save','Reopen'], expect:'Reporter field shows "Test Person".', roles:['all'], priority:'high'},
      {id:'tkt-018', title:'Anonymous checkbox strips reporter', pre:'User can make anonymous; new ticket', steps:['Tick Anonymous','Save','Reopen'], expect:'Reporter shows "Anonymous"; the name is blank.', roles:['admin','trustee'], priority:'high'},
      {id:'tkt-019', title:'Activity log records edits', pre:'Existing ticket', steps:['Change status','Change priority','Open activity log'], expect:'Both changes appear as log entries with timestamps and actor.', roles:['all'], priority:'high'},
      {id:'tkt-020', title:'Activity log collapses / expands', pre:'Ticket modal open', steps:['Click Activity Log header'], expect:'Toggle expands and collapses; caret ▶/▼ flips; entry count badge is visible.', roles:['all'], priority:'medium'},
      {id:'tkt-021', title:'Activity log default collapsed', pre:'Opening a ticket for the first time in this session', steps:['Open the ticket'], expect:'Activity log section is collapsed by default.', roles:['all'], priority:'low'},
      {id:'tkt-022', title:'Description supports long text', pre:'New ticket', steps:['Paste 2000+ characters into description','Save','Reopen'], expect:'Full text preserved; scrollable in modal.', roles:['all'], priority:'medium'},
      {id:'tkt-023', title:'Header shows ticket # + status pill + truncated description', pre:'Ticket with long description', steps:['Open the ticket'], expect:'Header line reads "Ticket # N [status pill] — <first 60 chars>…"', roles:['all'], priority:'low'},
      {id:'tkt-024', title:'Dates open/close save', pre:'Ticket modal open', steps:['Change Date Opened','Change Date Closed','Save','Reopen'], expect:'Both dates preserved.', roles:['admin','trustee'], priority:'medium'},
      {id:'tkt-025', title:'Ticket modal is mobile-friendly (below 760px)', pre:'Browser window narrower than 760px', steps:['Open a ticket'], expect:'Modal fills screen edge-to-edge; two-column layout stacks vertically; inputs are readable (no iOS auto-zoom).', roles:['all'], priority:'high'},
      {id:'tkt-026', title:'Filter chip: Open shows only open tickets', pre:'Multiple statuses of tickets exist', steps:['Click Open chip only','Deselect others'], expect:'Only open tickets shown.', roles:['all'], priority:'high'},
      {id:'tkt-027', title:'Filter chip: multi-select combines statuses', pre:'Multiple statuses exist', steps:['Select Open + In Progress'], expect:'Tickets in either status shown.', roles:['all'], priority:'medium'},
      {id:'tkt-028', title:'Search / free-text filter works', pre:'Search box available', steps:['Type a term matching a ticket title','Observe list'], expect:'List filters to matching tickets.', roles:['all'], priority:'high'},
      {id:'tkt-029', title:'Awaiting-approval cards have purple glow ring', pre:'Ticket in Awaiting Trustee Approval', steps:['View in card list'], expect:'Card has purple left border and pulsing purple ring animation.', roles:['all'], priority:'medium'},
      {id:'tkt-030', title:'Awaiting-approval cards show N/3 pill', pre:'Ticket in Awaiting Trustee Approval with 1 approval', steps:['View card in list'], expect:'Small pill "1 / 3 approvals" (amber) visible next to status badge.', roles:['all'], priority:'high'},
    ]
  },

  {
    id: 'approvals',
    name: 'Approvals & proposals',
    icon: '✓',
    tests: [
      {id:'app-001', title:'Approve a quote as trustee', pre:'Ticket in Awaiting Trustee Approval; user is trustee', steps:['Open ticket','Click ✓ Approve on a quote'], expect:'Green chip with trustee\'s name appears; per-item counter goes up by 1.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-002', title:'Revoke my approval', pre:'Trustee has already approved an item', steps:['Click × Revoke my approval'], expect:'Approval removed; chip disappears; counter decrements.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-003', title:'Threshold met turns pill green + shows Start Work', pre:'Two trustees have approved same quote; third trustee approves', steps:['Approve as third trustee','Look at header pill and per-item pill'], expect:'Both show "3 / 3 agreed" in green; a green "▶ Start Work" button appears on the item.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-004', title:'Start Work advances ticket to Work In Progress', pre:'Threshold met; user has canChangeStatus', steps:['Click Start Work on the approved item'], expect:'Ticket status advances; activity log records the item chosen; approval panel updates.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-005', title:'Approvals spread across items DO NOT meet threshold', pre:'Ticket has 2 quotes; 2 trustees on quote A, 1 on quote B, 0 elsewhere', steps:['Verify no Start Work button visible'], expect:'Threshold not met; no green button.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-006', title:'Header pill shows leading item count', pre:'Multiple items with different vote counts', steps:['Look at header pill'], expect:'Pill shows top-voted item count, e.g. "2 / 3 agreed (top item)".', roles:['all'], priority:'high'},
      {id:'app-007', title:'Approvers listed as chips', pre:'Item has 2 approvals', steps:['Look at approvers row on the item'], expect:'Two green chips with each trustee\'s name/username.', roles:['all'], priority:'medium'},
      {id:'app-008', title:'Add proposal as trustee', pre:'canManageCriteria = true; ticket in Awaiting Trustee Approval', steps:['Click + Add proposal','Type text','Submit'], expect:'New proposal appears with purple "PROPOSAL" badge and creator name.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-009', title:'Edit own proposal', pre:'User has a proposal they created', steps:['Click Edit on it','Change text','Save'], expect:'Text updated; other users see the change.', roles:['trustee','admin'], priority:'high'},
      {id:'app-010', title:'Delete own proposal', pre:'User has a proposal they created', steps:['Click Delete','Confirm'], expect:'Proposal removed from ticket; approvals on it also cleared.', roles:['trustee','admin'], priority:'high'},
      {id:'app-011', title:'Admin can edit any proposal', pre:'Admin; a trustee-created proposal exists', steps:['As admin, click Edit on the proposal'], expect:'Edit works even though admin did not create it.', roles:['admin'], priority:'medium'},
      {id:'app-012', title:'Cannot edit others\' proposals as trustee', pre:'Trustee not the creator', steps:['Try to click Edit on someone else\'s proposal'], expect:'Edit button hidden or edit is blocked.', roles:['trustee'], priority:'high'},
      {id:'app-013', title:'Approve a proposal counts toward threshold', pre:'Two proposals exist; two trustees approve one; third approves same', steps:['Verify per-item pill + header pill'], expect:'Threshold met on that proposal; Start Work button appears on it.', roles:['trustee','admin'], priority:'critical'},
      {id:'app-014', title:'Approvals work identically for quotes and proposals', pre:'Ticket has one quote + one proposal', steps:['Approve each in turn'], expect:'Same UI, same counters, no difference in behaviour.', roles:['trustee','admin'], priority:'high'},
      {id:'app-015', title:'Admin override — manually change status past approval', pre:'Ticket in Awaiting Trustee Approval, threshold NOT met', steps:['As admin, use the Status dropdown to force move to Work In Progress'], expect:'Status changes without requiring 3 votes.', roles:['admin'], priority:'high'},
      {id:'app-016', title:'Status set backwards from Work In Progress preserves proposals', pre:'Ticket in Work In Progress with proposals', steps:['Move status back to Awaiting Trustee Approval'], expect:'Proposals still visible; approvals may or may not persist (verify current behaviour).', roles:['admin'], priority:'medium'},
      {id:'app-017', title:'Approval-count pill shows on card in list', pre:'Ticket in Awaiting Trustee Approval', steps:['View list view'], expect:'Small "N / 3 approvals" pill visible on the card.', roles:['all'], priority:'high'},
      {id:'app-018', title:'Approval-count pill turns green ✓ 3/3 when met', pre:'Threshold met on ticket', steps:['View list view'], expect:'Pill shows "✓ 3 / 3" in green.', roles:['all'], priority:'high'},
      {id:'app-019', title:'Approval count pill NOT shown on non-awaiting statuses', pre:'Ticket in Open, In Progress, Work In Progress, or Resolved', steps:['View card in list'], expect:'Pill not shown.', roles:['all'], priority:'medium'},
      {id:'app-020', title:'Explainer text visible on approval panel', pre:'Awaiting Trustee Approval ticket open', steps:['Look at approval panel header area'], expect:'Text explains the 3-trustee-same-item rule.', roles:['all'], priority:'medium'},
      {id:'app-021', title:'Legacy no-quote-sentinel approvals still counted', pre:'Old ticket that has approvals but no attached quote (uses NO_QUOTE_SENTINEL)', steps:['Open the ticket'], expect:'A virtual criterion is synthesized; those approvals contribute to threshold.', roles:['all'], priority:'medium'},
      {id:'app-022', title:'Approve triggers log entry', pre:'Trustee approving an item', steps:['Approve','Check activity log'], expect:'Log entry "✓ Approved by <name> (quote/proposal: <label>)" or similar.', roles:['trustee','admin'], priority:'medium'},
      {id:'app-023', title:'Revoke triggers log entry', pre:'Trustee revoking an approval', steps:['Revoke','Check activity log'], expect:'Log entry "× Revoked by <name>".', roles:['trustee','admin'], priority:'medium'},
      {id:'app-024', title:'Start Work requires canChangeStatus', pre:'Threshold met but user has canChangeStatus = false', steps:['Look at the item'], expect:'Green Start Work button NOT shown; status can\'t be advanced by this user.', roles:['owner','tenant'], priority:'high'},
      {id:'app-025', title:'Approving does not double-count on rapid clicks', pre:'Trustee viewing approval panel', steps:['Click Approve rapidly 5 times'], expect:'Only one approval recorded; button becomes Revoke immediately.', roles:['trustee','admin'], priority:'high'},
    ]
  },

  {
    id: 'docs',
    name: 'Documents & attachments',
    icon: '📎',
    tests: [
      {id:'doc-001', title:'Attach photo via Gallery', pre:'Ticket modal open; user has canAttachFiles', steps:['Click 🖼 Gallery','Pick an image','Wait for upload'], expect:'Image compressed and uploaded; appears in the carousel.', roles:['admin','trustee','owner','tenant'], priority:'critical'},
      {id:'doc-002', title:'Attach photo via Camera (mobile)', pre:'On a mobile browser', steps:['Click 📷 Camera','Take a photo','Confirm'], expect:'Photo compressed and uploaded; appears in carousel.', roles:['all'], priority:'high'},
      {id:'doc-003', title:'Attach existing document by search', pre:'Ticket modal open; multiple existing invoices in system', steps:['Type in the "Search documents to link…" box','Pick a result'], expect:'Document linked to ticket; appears in list.', roles:['admin','trustee'], priority:'high'},
      {id:'doc-004', title:'Image carousel shows big preview', pre:'Ticket with 3 image attachments', steps:['Open ticket'], expect:'Big image preview at top of Linked Documents; thumbnail strip below.', roles:['all'], priority:'critical'},
      {id:'doc-005', title:'Carousel arrows navigate images', pre:'Ticket with 2+ images', steps:['Click › arrow','Then ‹ arrow'], expect:'Preview changes; thumbnail highlight moves; counter updates.', roles:['all'], priority:'high'},
      {id:'doc-006', title:'Thumbnail click jumps to image', pre:'Ticket with 3+ images', steps:['Click a thumbnail'], expect:'Big preview updates to that image; that thumbnail is highlighted purple.', roles:['all'], priority:'high'},
      {id:'doc-007', title:'Click big image opens lightbox', pre:'Ticket with images', steps:['Click the big preview'], expect:'Fullscreen dark lightbox opens with the image centred.', roles:['all'], priority:'critical'},
      {id:'doc-008', title:'Lightbox arrow keys navigate', pre:'Lightbox open with 2+ images', steps:['Press ← and → keys'], expect:'Image changes; counter updates.', roles:['all'], priority:'medium'},
      {id:'doc-009', title:'Lightbox Escape closes', pre:'Lightbox open', steps:['Press Escape'], expect:'Lightbox closes; underlying modal state preserved.', roles:['all'], priority:'medium'},
      {id:'doc-010', title:'Lightbox click-outside closes', pre:'Lightbox open', steps:['Click outside the image (dark area)'], expect:'Lightbox closes.', roles:['all'], priority:'medium'},
      {id:'doc-011', title:'Delete image via carousel ✕', pre:'User has canDeleteAttachments; image visible in carousel', steps:['Click ✕ on the big preview'], expect:'Image unlinked from ticket; carousel steps to next image or hides.', roles:['admin','trustee'], priority:'high'},
      {id:'doc-012', title:'Non-image docs show below carousel', pre:'Ticket with images AND a PDF', steps:['Open ticket'], expect:'Images in carousel up top; PDF in the compact card list below.', roles:['all'], priority:'high'},
      {id:'doc-013', title:'Open PDF in viewer', pre:'Ticket with PDF', steps:['Click the PDF card'], expect:'Viewer modal opens with PDF loaded; spinner while loading; iframe renders it.', roles:['all'], priority:'high'},
      {id:'doc-014', title:'Viewer spinner shows during image load', pre:'Ticket with a large image', steps:['Open ticket viewer for that image'], expect:'Purple spinner + "Loading image…" text visible until image ready; image fades in.', roles:['all'], priority:'medium'},
      {id:'doc-015', title:'Neighbour docs preloaded in carousel', pre:'Ticket with 3+ images; open viewer', steps:['Navigate to middle image → step to next'], expect:'Next image loads instantly (already cached).', roles:['all'], priority:'low'},
      {id:'doc-016', title:'Resync button visible for admin/trustee when linked docs exist', pre:'Ticket has linked docs; user is admin', steps:['Open ticket'], expect:'↑ Resync button in modal header.', roles:['admin','trustee'], priority:'high'},
      {id:'doc-017', title:'Resync fetches missing images from Supabase', pre:'Ticket has linked doc that admin\'s local cache doesn\'t have', steps:['Click Resync'], expect:'Feedback "✓ downloaded 1" or similar; image appears in carousel.', roles:['admin','trustee'], priority:'critical'},
      {id:'doc-018', title:'Resync pushes local-only docs up', pre:'Ticket has linked doc that exists locally but not on Supabase', steps:['Click Resync'], expect:'Feedback "✓ uploaded N"; other users can now see the doc.', roles:['admin','trustee'], priority:'high'},
      {id:'doc-019', title:'Missing-attachment warning banner for admin', pre:'Ticket has linked docs missing locally', steps:['Open ticket'], expect:'Orange banner "N attachment(s) isn\'t/aren\'t loaded locally. Click ↑ Resync above…"', roles:['admin','trustee'], priority:'high'},
      {id:'doc-020', title:'Missing-attachment warning banner for owner/tenant/viewer', pre:'Non-admin viewing ticket with missing attachments', steps:['Open ticket'], expect:'Warning explains an admin needs to resync.', roles:['owner','tenant','viewer'], priority:'medium'},
      {id:'doc-021', title:'Photos are compressed on upload', pre:'Large image (5MB+) available to upload', steps:['Attach it','Check network / final size'], expect:'Uploaded ≤~1MB JPEG (compression iterates quality down).', roles:['all'], priority:'high'},
      {id:'doc-022', title:'No linked docs → shows "No documents linked"', pre:'New ticket with no attachments', steps:['Open ticket'], expect:'Empty-state message shown; carousel/list hidden.', roles:['all'], priority:'medium'},
      {id:'doc-023', title:'Single image: no arrows or thumbnail strip', pre:'Ticket with exactly 1 image', steps:['Open ticket'], expect:'Big preview only; no navigation UI (no arrows, no counter, no thumbs).', roles:['all'], priority:'medium'},
      {id:'doc-024', title:'Carousel index persists per ticket', pre:'Ticket with 3 images; user is on image 2', steps:['Close modal','Reopen'], expect:'Carousel starts on image 2 again.', roles:['all'], priority:'low'},
      {id:'doc-025', title:'Carousel index resets when switching tickets', pre:'On image 3 of ticket A', steps:['Close A','Open ticket B (which has images)'], expect:'B starts on image 1.', roles:['all'], priority:'low'},
    ]
  },

  {
    id: 'suppliers',
    name: 'Suppliers',
    icon: '🏢',
    tests: [
      {id:'sup-001', title:'Create supplier', pre:'On Suppliers tab', steps:['Click +','Enter name, phone, email','Save'], expect:'Supplier appears in list.', roles:['admin','trustee'], priority:'critical'},
      {id:'sup-002', title:'Edit supplier fields', pre:'Existing supplier', steps:['Click it','Change phone, email, notes','Wait for auto-save (indicator flashes)'], expect:'Fields persist on reopen.', roles:['admin','trustee'], priority:'critical'},
      {id:'sup-003', title:'Delete supplier', pre:'Existing supplier open', steps:['Click Delete','Confirm'], expect:'Supplier removed from list.', roles:['admin','trustee'], priority:'high'},
      {id:'sup-004', title:'Rename supplier cascades to invoices', pre:'Supplier "ABC" has 3 linked invoices', steps:['Rename "ABC" to "ABC Ltd"','Save','Check the invoices'], expect:'All 3 invoices now show "ABC Ltd" as company; save indicator shows "(3 docs renamed)".', roles:['admin','trustee'], priority:'critical'},
      {id:'sup-005', title:'Ghost duplicate NOT created after rename', pre:'Just renamed supplier per above', steps:['Switch tabs','Return to Suppliers'], expect:'Only ONE supplier exists (not the renamed one AND a resurrected original).', roles:['admin','trustee'], priority:'critical'},
      {id:'sup-006', title:'importSuppliersFromInvoices creates missing suppliers', pre:'Invoice exists with invCompany that has no matching supplier record', steps:['Switch to Suppliers tab'], expect:'A new supplier auto-created with that name.', roles:['admin','trustee'], priority:'medium'},
      {id:'sup-007', title:'importSuppliersFromInvoices skips when modal open', pre:'Supplier modal open, editing', steps:['Wait — auto-import should not fire'], expect:'No duplicates created; edit continues cleanly.', roles:['admin','trustee'], priority:'high'},
      {id:'sup-008', title:'Supplier list is sortable/searchable', pre:'Multiple suppliers exist', steps:['Type in search box'], expect:'List filters to matches.', roles:['all'], priority:'medium'},
      {id:'sup-009', title:'Cannot save supplier with empty name', pre:'New supplier form', steps:['Leave name blank','Fill other fields','Try to save'], expect:'Save blocked or no-op.', roles:['admin','trustee'], priority:'medium'},
      {id:'sup-010', title:'Supplier data available when attaching a quote', pre:'Editing an invoice', steps:['Type in invCompany field','See if suppliers autocomplete'], expect:'Supplier suggestions appear as user types.', roles:['admin','trustee'], priority:'low'},
      {id:'sup-011', title:'Supplier notes preserved on save', pre:'Editing supplier', steps:['Add multi-line notes','Wait for auto-save','Reload','Reopen'], expect:'Notes preserved verbatim.', roles:['admin','trustee'], priority:'medium'},
      {id:'sup-012', title:'Supplier phone/email display in invoice context', pre:'Invoice linked to supplier with contact info', steps:['View the invoice'], expect:'Supplier contact info shown or available for reference.', roles:['all'], priority:'low'},
      {id:'sup-013', title:'Renaming supplier updates in real time', pre:'Multiple browser tabs open on same ticket', steps:['Rename supplier in tab A','Refresh tab B'], expect:'Tab B sees renamed supplier.', roles:['admin','trustee'], priority:'low'},
      {id:'sup-014', title:'Case-insensitive supplier name matching in imports', pre:'Invoice invCompany "abc plumbing" and supplier "ABC Plumbing"', steps:['Trigger import'], expect:'No duplicate — treated as the same supplier.', roles:['admin','trustee'], priority:'medium'},
      {id:'sup-015', title:'Whitespace-tolerant supplier matching', pre:'Invoice "ABC  Plumbing" (extra spaces) and supplier "ABC Plumbing"', steps:['Trigger import'], expect:'Whitespace trimmed; no duplicate.', roles:['admin','trustee'], priority:'low'},
    ]
  },

  {
    id: 'public',
    name: 'Public form (no-login)',
    icon: '🌐',
    tests: [
      {id:'pub-001', title:'?contact-public opens the public form', pre:'Not logged in', steps:['Visit ?contact-public'], expect:'Public submission form loads; no login modal.', roles:['unauth'], priority:'critical'},
      {id:'pub-002', title:'Legacy ?report=1 still works', pre:'Not logged in', steps:['Visit ?report=1'], expect:'Same public form loads (backwards compat).', roles:['unauth'], priority:'high'},
      {id:'pub-003', title:'Public form is admin-disable-able', pre:'Admin toggles Public reporting OFF', steps:['Visit ?contact-public as guest'], expect:'"Submissions currently disabled" message shown; no form.', roles:['unauth'], priority:'critical'},
      {id:'pub-004', title:'Admin toggle URL updates', pre:'Admin in Settings → Public reporting', steps:['Toggle ON','Check URL displayed'], expect:'URL shows ?contact-public (not ?report=1).', roles:['admin'], priority:'high'},
      {id:'pub-005', title:'Copy URL button copies', pre:'Public reporting ON', steps:['Click Copy in Settings'], expect:'Button flashes "✓ Copied"; URL is in clipboard.', roles:['admin'], priority:'high'},
      {id:'pub-006', title:'Submit with all fields', pre:'Public form open', steps:['Fill subject, details, unit, name, email, phone','Attach 1 photo','Submit'], expect:'Success screen; personal link shown; ticket appears in admin\'s list.', roles:['unauth'], priority:'critical'},
      {id:'pub-007', title:'Submit with minimum fields', pre:'Public form open', steps:['Fill subject + details only','Submit'], expect:'Success; ticket created with reporter "Anonymous".', roles:['unauth'], priority:'critical'},
      {id:'pub-008', title:'Empty subject rejected', pre:'Public form open', steps:['Leave subject blank','Fill details','Submit'], expect:'Error "Please give your message a short subject."', roles:['unauth'], priority:'high'},
      {id:'pub-009', title:'Empty details rejected', pre:'Public form open', steps:['Fill subject','Leave details blank','Submit'], expect:'Error "Please add some details."', roles:['unauth'], priority:'high'},
      {id:'pub-010', title:'Bad email format rejected', pre:'Public form open', steps:['Enter "foo" in email field','Submit'], expect:'Error about email format.', roles:['unauth'], priority:'medium'},
      {id:'pub-011', title:'Empty email OK when not opted in', pre:'Public form open', steps:['Fill required fields','Leave email blank','Do NOT tick email-me-link','Submit'], expect:'Success; no email sent.', roles:['unauth'], priority:'high'},
      {id:'pub-012', title:'Email opt-in requires email', pre:'Public form open', steps:['Tick "📧 Email me my edit link"','Leave email blank','Submit'], expect:'Error requiring email field.', roles:['unauth'], priority:'high'},
      {id:'pub-013', title:'Email opt-in sends email via Resend', pre:'RESEND_API_KEY set; email verified in Resend', steps:['Fill form','Tick opt-in','Use verified email','Submit'], expect:'Status pill "📧 Sending…" → "✓ Sent to <email>"; email arrives.', roles:['unauth'], priority:'critical'},
      {id:'pub-014', title:'Email send failure shows amber warning', pre:'Bad API key or unverified recipient', steps:['Submit with opt-in'], expect:'Amber "⚠ Could not send the email right now" message; personal link still shown on screen.', roles:['unauth'], priority:'high'},
      {id:'pub-015', title:'Photo limit 5 enforced', pre:'Public form open', steps:['Attach 6 photos','Submit'], expect:'Error "A maximum of 5 photos can be attached."', roles:['unauth'], priority:'high'},
      {id:'pub-016', title:'Honeypot field silently drops bot submits', pre:'Simulate by setting the hidden #pub-honey field via devtools', steps:['Fill valid form','Set pub-honey value','Submit'], expect:'Fake success screen; no ticket actually created.', roles:['unauth'], priority:'medium'},
      {id:'pub-017', title:'Rate limit blocks 4th submission per hour', pre:'Public form; already submitted 3 times this hour from this browser', steps:['Try 4th submit'], expect:'Error "You\'ve submitted several reports recently. Please wait…"', roles:['unauth'], priority:'medium'},
      {id:'pub-018', title:'Personal link shown after submit', pre:'Just submitted', steps:['Look at success screen'], expect:'"Your personal link…" box with the URL and Copy button.', roles:['unauth'], priority:'critical'},
      {id:'pub-019', title:'Copy link button on success screen', pre:'On success screen', steps:['Click Copy link'], expect:'Button flashes "✓ Copied"; URL in clipboard.', roles:['unauth'], priority:'high'},
      {id:'pub-020', title:'iOS Copy fallback selects the URL', pre:'On iPhone Safari; Copy triggered', steps:['Click Copy','Observe URL area'], expect:'URL text is selected on screen; user can iOS-Copy manually.', roles:['unauth'], priority:'medium'},
      {id:'pub-021', title:'Personal edit link loads existing submission', pre:'Have a valid ?reportEdit=<token>', steps:['Visit the URL'], expect:'Form loads pre-populated with the submitted data.', roles:['unauth'], priority:'critical'},
      {id:'pub-022', title:'Invalid token shows "Link not found"', pre:'Fabricated bogus token', steps:['Visit ?reportEdit=fake-token'], expect:'Friendly error page; no form.', roles:['unauth'], priority:'high'},
      {id:'pub-023', title:'Edit form allows changing all fields', pre:'Edit form open on Open-status ticket', steps:['Change subject, details, unit, name, email, phone','Save'], expect:'"Saved" screen; changes persist on reopen.', roles:['unauth'], priority:'critical'},
      {id:'pub-024', title:'Edit form shows existing photos as thumbnails', pre:'Ticket with 3 photos; open edit view', steps:['Look at photos section'], expect:'3 × 96px thumbnails with ✕ delete buttons.', roles:['unauth'], priority:'high'},
      {id:'pub-025', title:'Tap thumbnail → fullscreen preview', pre:'Photos in edit view', steps:['Tap a thumbnail'], expect:'Fullscreen overlay with × close button.', roles:['unauth'], priority:'medium'},
      {id:'pub-026', title:'Delete existing photo (✕ marks pending)', pre:'Photo in edit view', steps:['Click ✕ on a photo'], expect:'Photo greys out; ✕ becomes ↺ (undo).', roles:['unauth'], priority:'high'},
      {id:'pub-027', title:'Undo pending delete (↺)', pre:'A photo is marked for delete', steps:['Click the ↺ button'], expect:'Photo un-greys; button becomes ✕ again.', roles:['unauth'], priority:'medium'},
      {id:'pub-028', title:'Save applies pending deletes', pre:'Marked photos for delete', steps:['Save'], expect:'Deleted photos gone on reopen; log entry mentions removal.', roles:['unauth'], priority:'high'},
      {id:'pub-029', title:'Total photo cap 5 across old + new', pre:'3 photos already; delete 1; try to add 3 new', steps:['Save'], expect:'Error total cap exceeded (2 existing + 3 new = 5, allowed; 3 existing + 3 new = 6, blocked).', roles:['unauth'], priority:'high'},
      {id:'pub-030', title:'Locked when status leaves Open', pre:'Admin moves ticket to In Progress', steps:['Public submitter revisits ?reportEdit URL'], expect:'Read-only view; explanation that a trustee has started work.', roles:['unauth'], priority:'critical'},
      {id:'pub-031', title:'"Back to my submission" button works after save', pre:'Just saved an edit', steps:['Click Back to my submission'], expect:'Returns to editable form.', roles:['unauth'], priority:'high'},
      {id:'pub-032', title:'Read-only view shows photos + description', pre:'Ticket past Open status', steps:['Visit ?reportEdit'], expect:'Description, unit, reporter, photos shown; no editable fields.', roles:['unauth'], priority:'high'},
      {id:'pub-033', title:'🌐 Public badge on admin cards', pre:'Public submission exists', steps:['View ticket list as admin'], expect:'"🌐 Public" pill visible on that card.', roles:['admin','trustee'], priority:'high'},
      {id:'pub-034', title:'Reporter phone/email fields populated on admin modal', pre:'Public submission with phone/email', steps:['Open the ticket as admin'], expect:'Phone and Email fields under reporter name are pre-filled.', roles:['admin','trustee'], priority:'high'},
      {id:'pub-035', title:'Admin can edit reporter contact info', pre:'Ticket modal open', steps:['Change phone or email','Wait for auto-save'], expect:'Change persists.', roles:['admin','trustee'], priority:'medium'},
    ]
  },

  {
    id: 'usermgmt',
    name: 'User management & linking',
    icon: '👥',
    tests: [
      {id:'usr-001', title:'Create new user', pre:'Admin in Settings → Users', steps:['Click new user','Fill username, full name, role, password','Save'], expect:'User in list; can immediately log in.', roles:['admin'], priority:'critical'},
      {id:'usr-002', title:'Edit existing user', pre:'Admin viewing a user', steps:['Change name, phone, email','Save'], expect:'Changes persist.', roles:['admin'], priority:'critical'},
      {id:'usr-003', title:'Delete user', pre:'Admin viewing a user', steps:['Delete','Confirm'], expect:'User removed from list; can no longer log in.', roles:['admin'], priority:'high'},
      {id:'usr-004', title:'Cannot delete self', pre:'Admin editing own record', steps:['Look for Delete'], expect:'Delete button hidden or disabled for own record.', roles:['admin'], priority:'high'},
      {id:'usr-005', title:'Change user role', pre:'Editing a user', steps:['Change role from owner to trustee','Save','Log in as that user'], expect:'That user now has trustee capabilities.', roles:['admin'], priority:'critical'},
      {id:'usr-006', title:'Link ticket to user — dropdown visible for admin/trustee', pre:'Ticket with no reporterUserId; admin/trustee viewing', steps:['Open modal','Look below reporter fields'], expect:'"🔗 Link to existing user" dropdown appears.', roles:['admin','trustee'], priority:'high'},
      {id:'usr-007', title:'Link ticket to user — NOT visible for owner/tenant/viewer', pre:'Same as above but user is an owner or tenant', steps:['Open modal'], expect:'Dropdown not visible.', roles:['owner','tenant','viewer'], priority:'high'},
      {id:'usr-008', title:'Selecting a user links ticket', pre:'Dropdown showing user options', steps:['Pick a user'], expect:'Reporter name replaced by user\'s full name; green "🔗 Linked to X" badge appears; dropdown disappears; log entry added.', roles:['admin','trustee'], priority:'critical'},
      {id:'usr-009', title:'Linking pulls contact info from user record', pre:'Linking to a user with email/phone; ticket has none', steps:['Link'], expect:'Ticket\'s email and phone fields populated from user record.', roles:['admin','trustee'], priority:'high'},
      {id:'usr-010', title:'Linking does NOT overwrite existing contact', pre:'Ticket has phone/email from public submitter; linking to user with different phone', steps:['Link'], expect:'Existing contact preserved; user\'s not overwritten.', roles:['admin','trustee'], priority:'high'},
      {id:'usr-011', title:'Linked ticket persists across saves', pre:'Ticket linked to user', steps:['Change other fields','Save','Reopen'], expect:'Link still intact (reporterUserId preserved).', roles:['admin','trustee'], priority:'critical'},
      {id:'usr-012', title:'Unlink button visible for admin only', pre:'Linked ticket open; user is trustee', steps:['Look at the linked badge'], expect:'No unlink button (only admin sees it).', roles:['trustee'], priority:'high'},
      {id:'usr-013', title:'Admin unlink returns dropdown', pre:'Linked ticket open as admin', steps:['Click unlink','Confirm'], expect:'Green badge disappears; dropdown reappears; reporter name STAYS as-is; log entry added.', roles:['admin'], priority:'high'},
      {id:'usr-014', title:'Guest role excluded from link dropdown', pre:'Admin linking; users include one with role=guest', steps:['Open dropdown'], expect:'Guest not in list.', roles:['admin','trustee'], priority:'medium'},
      {id:'usr-015', title:'No-users case shows placeholder message', pre:'No users in system except admin', steps:['Open dropdown area'], expect:'"No users on file to link to" text shown.', roles:['admin','trustee'], priority:'low'},
    ]
  },

  {
    id: 'sharing',
    name: 'Sharing & external links',
    icon: '🔗',
    tests: [
      {id:'shr-001', title:'Share link button generates URL', pre:'Ticket open; user has canShareLink', steps:['Click Share link'], expect:'Modal shows a URL; Copy button; can revoke.', roles:['admin','trustee'], priority:'critical'},
      {id:'shr-002', title:'Share URL opens read-only view', pre:'Valid share URL known', steps:['Log out','Visit the URL'], expect:'Ticket details displayed read-only; no login modal.', roles:['unauth'], priority:'critical'},
      {id:'shr-003', title:'Revoked share URL stops working', pre:'Share URL exists; then admin revokes it', steps:['Visit URL after revoke'], expect:'"Link not available" error.', roles:['unauth'], priority:'high'},
      {id:'shr-004', title:'Share view respects Copyright — no editing', pre:'On shared view', steps:['Look for edit controls'], expect:'No status changes, no approve buttons, no delete — read-only.', roles:['unauth'], priority:'critical'},
      {id:'shr-005', title:'Share and edit tokens are SEPARATE', pre:'Same ticket has both a share link and a public edit token', steps:['Verify tokens are different strings'], expect:'Two independent tokens; changing one doesn\'t affect the other.', roles:['unauth'], priority:'high'},
      {id:'shr-006', title:'Share link Copy button works', pre:'Share modal open', steps:['Click Copy'], expect:'URL in clipboard; flash "✓ Copied".', roles:['admin','trustee'], priority:'high'},
      {id:'shr-007', title:'Share link footer identifies as shared view', pre:'Viewing shared ticket', steps:['Scroll to footer'], expect:'"Park Manor Body Corporate — shared view" text.', roles:['unauth'], priority:'low'},
    ]
  },

  {
    id: 'ui',
    name: 'UI, theme, and misc',
    icon: '🎨',
    tests: [
      {id:'ui-001', title:'Theme button opens picker menu with 7 themes', pre:'Logged in', steps:['Click the theme icon in the header'], expect:'A dropdown menu appears listing Midnight, Slate, Graphite, Ocean, Daylight, Sage, and Clean — each with a colour swatch. The current theme is highlighted with a ✓. Clicking a theme applies it instantly; clicking outside closes the menu.', roles:['all'], priority:'medium'},
      {id:'ui-002', title:'Theme preference persists across reloads', pre:'Set theme to light', steps:['Reload page'], expect:'Theme still light.', roles:['all'], priority:'medium'},
      {id:'ui-003', title:'Green theme uses muted sage colours', pre:'On green theme', steps:['Look at UI'], expect:'Backgrounds are pale green tones; accents still purple.', roles:['all'], priority:'low'},
      {id:'ui-004', title:'Settings modal opens for admin', pre:'Admin', steps:['Click ⚙ Settings'], expect:'Modal opens with tabs / sections.', roles:['admin'], priority:'critical'},
      {id:'ui-005', title:'Header logout button visible', pre:'Logged in', steps:['Look at header'], expect:'Logout button in header/menu.', roles:['all'], priority:'high'},
      {id:'ui-006', title:'Feedback: thumbs-down mentioned in refusals', pre:'Attempt a blocked action', steps:['Trigger permission-denied case'], expect:'User is guided to feedback via thumbs-down (aspirational — verify).', roles:['all'], priority:'low'},
      {id:'ui-007', title:'iOS input font-size 16px prevents auto-zoom', pre:'iPhone Safari', steps:['Focus a text input'], expect:'Page does NOT auto-zoom; input stays at same visual scale.', roles:['all'], priority:'high'},
      {id:'ui-008', title:'Mobile modal fills screen (< 760px)', pre:'Narrow window', steps:['Open a ticket modal'], expect:'Modal takes full screen, not centred with margin.', roles:['all'], priority:'high'},
      {id:'ui-009', title:'deploy.txt exists at site root', pre:'Any deploy state', steps:['Visit /deploy.txt directly'], expect:'Shows a UTC timestamp of last build.', roles:['all'], priority:'medium'},
      {id:'ui-010', title:'App renders without JavaScript errors', pre:'Fresh page load', steps:['Open browser dev console','Load app','Login'], expect:'No red errors in console.', roles:['all'], priority:'high'},
    ]
  },

  {
    id: 'rolesplit',
    name: 'Owner / Tenant role split',
    icon: '\ud83c\udfe0',
    tests: [
      {id:'split-001', title:'Add User modal shows Owner card, not Resident', pre:'Logged in as admin', steps:['Users tab \u2192 Add User','Look at the role cards'], expect:'An Owner \ud83c\udfe0 card (green) and a Tenant \ud83d\udd11 card (teal) are shown. There is NO Resident card.', roles:['admin'], priority:'critical'},
      {id:'split-002', title:'Create an Owner user', pre:'Add User modal open', steps:['Select Owner','Set username/password/name','Add a unit number','Save'], expect:'User saves with role owner; appears in Users list with a green \ud83c\udfe0 OWNER badge.', roles:['admin'], priority:'critical'},
      {id:'split-003', title:'Create a Tenant user', pre:'Add User modal open', steps:['Select Tenant','Set username/password/name','Add a unit number','Save'], expect:'User saves with role tenant; appears in Users list with a teal \ud83d\udd11 TENANT badge.', roles:['admin'], priority:'critical'},
      {id:'split-004', title:'Units + image-permission sections appear for both roles', pre:'Add/Edit User modal open', steps:['Select Owner \u2014 observe sections','Select Tenant \u2014 observe sections'], expect:'Unit assignment and the can-add-images checkbox are shown for BOTH Owner and Tenant, exactly as they were for Resident.', roles:['admin'], priority:'high'},
      {id:'split-005', title:'Owner login lands on Tickets tab only', pre:'Owner user exists', steps:['Log in as the owner'], expect:'First tab is Tickets; all other tabs (transactions, expenses, income, invoices, suppliers, resolutions, users, recon) are hidden. Logout button reads \u201c\u2713 <name> (Owner)\u201d.', roles:['owner'], priority:'critical'},
      {id:'split-006', title:'Tenant login lands on Tickets tab only', pre:'Tenant user exists', steps:['Log in as the tenant'], expect:'Same as owner: Tickets tab only. Logout button reads \u201c\u2713 <name> (Tenant)\u201d.', roles:['tenant'], priority:'critical'},
      {id:'split-007', title:'Owner sees only own-unit / own-created tickets', pre:'Owner assigned unit X; tickets exist for unit X and unit Y', steps:['Log in as owner','View ticket list'], expect:'Only unit-X tickets and tickets they created are listed; unit-Y tickets hidden.', roles:['owner'], priority:'critical'},
      {id:'split-008', title:'Tenant sees only own-unit / own-created tickets', pre:'Tenant assigned unit X; tickets exist for unit X and unit Y', steps:['Log in as tenant','View ticket list'], expect:'Only unit-X tickets and tickets they created are listed; unit-Y tickets hidden.', roles:['tenant'], priority:'critical'},
      {id:'split-009', title:'Owner and Tenant behave identically (for now)', pre:'One owner and one tenant user, same unit', steps:['Log in as each in turn','Open the same ticket','Compare available actions'], expect:'Both see identical controls: delete own tickets only, attach files, anonymous reporting, no status changes, no approvals.', roles:['owner','tenant'], priority:'high'},
      {id:'split-010', title:'Legacy resident user still logs in unchanged', pre:'A user with role resident still exists in Supabase (created before the split)', steps:['Log in as that user'], expect:'Login works; Tickets-only view; own-unit scoping; behaviour identical to before the split.', roles:['all'], priority:'critical'},
      {id:'split-011', title:'Editing a legacy resident prompts a role choice', pre:'Admin edits a legacy resident user', steps:['Open their Edit User modal','Observe role cards','Try saving without selecting'], expect:'No card is pre-selected (Resident card is gone). Saving without a selection shows \u201cSelect a role.\u201d \u2014 admin must choose Owner or Tenant, which migrates the record.', roles:['admin'], priority:'high'},
      {id:'split-012', title:'Permissions matrix shows owner, tenant, and resident columns', pre:'Logged in as admin', steps:['Settings \u2192 Permissions'], expect:'Columns: trustee, owner, tenant, resident, viewer, guest. Owner and tenant start with identical values (own deletes, attach files, anonymous on).', roles:['admin'], priority:'high'},
      {id:'split-013', title:'Owner and Tenant permissions can diverge independently', pre:'Permissions matrix open', steps:['Change one tenant permission (e.g. canAttachFiles off)','Apply','Log in as tenant, then as owner'], expect:'Tenant loses the ability; owner is unaffected. Revert afterwards.', roles:['admin'], priority:'high'},
      {id:'split-014', title:'Meeting attendee badges distinguish O and Tn', pre:'Owner and tenant users exist; meeting modal open', steps:['Open attendee picker'], expect:'Owner chip shows green O badge; tenant chip shows teal Tn badge.', roles:['admin','trustee'], priority:'medium'},
      {id:'split-015', title:'Public report edit-links still work for owner/tenant reporters', pre:'Owner submits a ticket via ?contact-public with edit link', steps:['Use the ?reportEdit=<token> link'], expect:'Edit form loads exactly as it did for residents.', roles:['unauth'], priority:'medium'},
    ]
  }
];
